### ISSUE TITLE
Default pluralization resolvers are missing when using auto plural detection

### ISSUE THREAD

**Issue by Tienisto** [Tienisto/flutter-fast-i18n#16]
When using auto plural detection, then pluralization resolvers are not rendered.

Configuration:
```yaml
fast_i18n:i18nBuilder:
  enabled: true
  options:
   pluralization:
      auto: cardinal
```
