### ISSUE TITLE
Custom Contexts

### ISSUE THREAD

**Issue by Tienisto** [Tienisto/flutter-fast-i18n#17]
This is an idea for the next feature introducing custom contexts.

**Motivation**
There should be an option to differentiate between male and female forms. It should be generic so we can add more use cases.

**Developer Experience**
Similar to pluralization, there should be an additional parameter. Here it will be `context`.
```json
{
  "welcome": {
    "male": "Mr $name",
    "female": "Ms $name"
  }
}
```
```dart
String a = t.welcome(name: 'Tom', context: GenderContext.male);
```
The enum should be configurable. There can be more than one context type.
```yaml
targets:
  $default:
    builders:
      fast_i18n:i18nBuilder:
        options:
          contexts:
            gender_context:  # The resulting enum will be in pascal case, i.e. "GenderContext"
              enum:
                - male
                - female
              auto: false
              paths:
                - welcome
            polite_context:  # Imaginary context type called "PoliteContext"
              enum:
                - polite
                - neutral
                - rude
              auto: on
```
Some languages may have fewer context types, therefore we may collapse them:
```json
{
  "welcome": {
    "male,female": "$name"
  }
}
```
