### ISSUE TITLE
'PluralResolver' not found in 5.0.0

### ISSUE THREAD

**Issue by dluksza** [Tienisto/flutter-fast-i18n#28]
After migrating to 5.0.0 the generated `d.dart` file is not compiling in my project. It is throwing a type errors
```
lib/l10n/messages.g.dart:136:59: Error: 'PluralResolver' isn't a type.
	static void setPluralResolver({required String language, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver}) {
	                                                        ^^^^^^^^^^^^^^
lib/l10n/messages.g.dart:136:93: Error: 'PluralResolver' isn't a type.
	static void setPluralResolver({required String language, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver}) {
	                                                                                          ^^^^^^^^^^^^^^
lib/l10n/messages.g.dart:137:33: Error: Getter not found: '_pluralResolversCardinal'.
		if (cardinalResolver != null) _pluralResolversCardinal[language] = cardinalResolver;
		                             ^^^^^^^^^^^^^^^^^^^^^^^^
lib/l10n/messages.g.dart:138:32: Error: Getter not found: '_pluralResolversOrdinal'.
		if (ordinalResolver != null) _pluralResolversOrdinal[language] = ordinalResolver;
```

Here's my configuration in `build.yaml` 
```yaml
targets:
  $default:
    builders:
      fast_i18n:
        options:
          input_directory: res/l10n
          output_directory: lib/l10n
          translation_class_visibility: public
```
