### ISSUE TITLE
Dollar symbol is not escaped for braces string interpolations

### ISSUE THREAD

**Issue by mjablecnik** [Tienisto/flutter-fast-i18n#33]
Without build.yaml config command `flutter pub run fast_i18n` generate this class:
![image](https://user-images.githubusercontent.com/2686906/132190778-2b69e503-d3ff-415a-b171-67fc67caa9fc.png)

But when I add build.yaml with:
```
targets:
  $default:
    builders:
      fast_i18n:
        options:
          base_locale: cs
          translate_var: translate
          key_case: camel
          string_interpolation: double_braces
```
so it generate:
![image](https://user-images.githubusercontent.com/2686906/132191028-15471285-cebc-455f-91bc-da81dd2d62b4.png)

Where name is undefined variable because `$` symbol is not escaped by `\$`.

My strings.i18n.json is:
```
{
  "title": "Scanner pro vážení balíků",
  "scanner_informations": "Scanner informations",
  "scale_informations": "Scale informations",
  "hello": "Hello $name",
  "save": "Save",
  "login": {
    "fail": "Logged in failed"
  }
}

```
