### ISSUE TITLE
String interpolation does not apply camel key case to method arguments

### ISSUE THREAD

**Issue by scopendo** [Tienisto/flutter-fast-i18n#34]
Thank you for this helpful package.

I've noticed that if I use `{snake_case}` in my translation strings, that the corresponding method does not apply camel case to the method's named parameters.  For example, given the following translation string:

```json
{
  "visit_status": "{status_text} at {when}"
}
```

I would expect the following method signature to be generated with the named parameter `statusText` having camel case applied.

```dart
  String visitStatus({required Object statusText, required Object when}) => '$statusText at $when';
```

However, the following method signature is generated where the snake case has not been converted to camel case.

```dart
  String visitStatus({required Object status_text, required Object when}) => '$status_text at $when';
```

My `build.yaml` file is:

```yaml
targets:
  $defaults:
    builders:
      fast_i18n:
        options:
          fallback_strategy: base_locale
          input_directory: lib/localizations
          output_directory: lib/localizations
          key_case: camel
          string_interpolation: braces
```
