### ISSUE TITLE
Setting default language

### ISSUE THREAD

**Issue by n-kulic** [Tienisto/flutter-fast-i18n#44]
To set a default language, a configuration was made in `build.yaml` file, where `base_locale` was set to **hr**
```yaml
targets:
  $default:
    builders:
      fast_i18n:
        options:
          base_locale: hr #<<<<<
          fallback_strategy: base_locale
          input_directory: lib/core/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/core/i18n
          output_file_pattern: .g.dart
          translate_var: tr
          enum_name: AppLocale
          translation_class_visibility: private
```
Configuration along with generated dart code is as following:
![image](https://user-images.githubusercontent.com/94164339/141780687-9ca25230-de20-41e9-99fc-e4c1c6febf11.png)

The issue is at the startup when translation is fetched from json file, it does not get translation from default language/base_locale as it should, but rather it displays English translation _**(Loyalty club):**_
```dart
Text(tr.landing.benefitsClub), // displays "Loyalty club"
```

![image](https://user-images.githubusercontent.com/94164339/141781127-f30b3192-9f8a-42a9-89fb-c994f7f34e93.png)
