### ISSUE TITLE
key_map_case is ignored in 5.6.0

### ISSUE THREAD

**Issue by vladaman** [Tienisto/flutter-fast-i18n#47]
Affected version: 5.6.0

Setting following in build.yaml does not seem to have effect on generated maps case:
```yaml
      key_map_case: pascal
      flat_map: false
      maps:
        - ProjectActivityType
        - AddressBookType
```

1. When flat_map is false it does not generate any maps in strings.g.dart
2. Even when flat_map is enabled to true than the `key_map_case` case transformation is ignored.

JSON:
```json
{
  "AddressBookType": {
    "COMPANY": "Company",
    "PERSON": "Person"
  }
}
```
will produce nin strings.g.dart:
```dart
AppLocale.cs: {
  'addressBookType.company': 'Firma',
  'addressBookType.person': 'Osoba',
}

**Comment by Tienisto** [comment]
Hi,

The flat map at the end of the generated `.g.dart` can be turned off by setting `flat_map` to `false`. It should work as you said.
Did you configure `key_case: camel`? Then the maps should also follow the case:

```yaml
key_case: camel
key_map_case: pascal
flat_map: false
  maps:
    - projectActivityType
    - addressBookType
```

**Comment by vladaman** [comment]
Thanks, but still doesn't seem to work as we expect. With following example we'd expect the flat map will be generted just for maps mentioned in the list. Neither of them work. None of the maps is generated. We'd expect the regular keys be converted into camel case, and maps for these objects generated with Pascal case.

```yaml
          key_case: camel
          key_map_case: pascal
          flat_map: false
          maps:
            - ProjectActivityType
            - AddressBookType
            - addressBookType
```

**Comment by Tienisto** [comment]
You mean this following map?
```text
AppLocale.cs: {
  'addressBookType.company': 'Firma',
  'addressBookType.person': 'Osoba',
}
```

Then `flat_map` needs to be true. The flat map is the map containing all translations regardless of "map" or "not map"

**Comment by Tienisto** [comment]
It seems to be alright on my side.

**Comment by vladaman** [comment]
Sorry @Tienisto  , but I am still having issues. My config is:
```yaml
key_case: camel
key_map_case: snake
flat_map: true
maps:
   - ProjectActivityType
   - AddressBookType
   - FieldType
```

But unfortunately the maps in strings.g.dart are **still translated to**:

```
'fieldType.lplate': 'License plate',
'fieldType.desc': 'Description',
'fieldType.contactInvestor': 'Contact Investor',
```

In .json file we have following:
```json
"FieldType": {
 "LPLATE": "License plate",
 "DESC": "Description",
 "CONTACT_INVESTOR": "Contact Investor",
```

I would expect the map keys to be in snake case but it's not. But our use case is different. We'd like to use camel case but ONLY for maps to disable any text transformations. Reason is we use enums like:

```dart
// The key will be "FieldType.LPLATE"
labelText: t[FieldType.LPLATE.toString()]
```

**Comment by Tienisto** [comment]
Alright,

currently, it is not possible to have different cases.

`key_map_case` only applies to local maps (i.e. `t.error['camel_case']`).

I think a new configuration `flat_map_key_case` should be implemented.

**Comment by Tienisto** [comment]
I think there is no elegant solution for your problem.

`FieldType.LPLATE.toString()` will be probably calculated as `FieldType.LPLATE`. This string contains 2 different cases.

The best solution would be to use the new dart enum feature: `FieldType.LPLATE.name`. Then you will get `LPLATE`.

Then use the following config:

```yaml
key_case: pascal
# do not set key_map_case, so we retain the UPPERCASE_SNAKE case
maps:
  - FieldType
```

```dart
String a = t.FieldType['CONTACT_INVESTOR'];
```
