### ISSUE TITLE
Unable to access value with dynamic keys

### ISSUE THREAD

**Issue by n-kulic** [Tienisto/flutter-fast-i18n#50]
When trying to access translation value by dynamic key I'm getting error that says 

> _The operator '[]' isn't defined for the type '_StringsLanguagesHr'._
> _Try defining the operator '[]'_

```dart
tr.languages['hr'] // error here
```
** **
`// File: strings.i18n.json`
```json
  "languages": {
    "hr": "Hrvatska",
    "us": "SAD"
  }
```
![image](https://user-images.githubusercontent.com/94164339/147279328-ee3b552b-d62a-4c10-a8a7-7ea3dc13e831.png)

**Comment by n-kulic** [comment]
I realized i can access it dynamically from root
```dart
tr['languages.hr'] 
```

That would be solved then

**Comment by Tienisto** [comment]
Hi,
alternatively, you can specify maps in the `build.yaml` :)

```yaml
targets:
  $default:
    builders:
      fast_i18n:
        options:
          maps:
            - languages
```
