### ISSUE TITLE
Namespaces bug

### ISSUE THREAD

**Issue by mjablecnik** [Tienisto/flutter-fast-i18n#54]
Hello, I experiment with namespaces for split my one input file into more files.
I had in `strings.i18n.json` this json structure:
```
{
  "core": {
    ...
  },
  "app": {
    "title": "Example App",
    ...
  },
  "auth": {
    ...
  },
  "barcode_registration": {
    ...
  }
}
```
And I split it into this folder structure:
![image](https://user-images.githubusercontent.com/2686906/153414506-e22d0101-ba1b-4d99-bf66-c8cd1c74793c.png)

But when I run `flutter pub run fast_i18n ` command so it generate translations only for core, app and auth but
translations in barcode_registration section is not generated..:
![image](https://user-images.githubusercontent.com/2686906/153415046-c2aa1e65-f746-4638-afa8-18c527d971d4.png)

Probably there is a problem with `_` and it doesn't create `barcodeRegistration` property.
![image](https://user-images.githubusercontent.com/2686906/153415355-8fe82f4e-f072-49aa-a398-e908378b449c.png)

Can you fix it please?

Here is my `build.yaml` configuration:
```
targets:
  $default:
    builders:
      fast_i18n:
        options:
          base_locale: cs
          translate_var: translate
          key_case: camel
          key_map_case: camel
          param_case: camel
          string_interpolation: double_braces
          input_directory: lib/core/i18n
          namespaces: true
          output_format: multiple_files
          output_file_name: strings.g.dart
          output_directory: lib/core/i18n
          maps:
            - core.changeLanguage.languages
```

Thank you very much.
