### ISSUE TITLE
Empty lists not handled properly

### ISSUE THREAD

**Issue by Tienisto** [Tienisto/flutter-fast-i18n#59]
**Describe the bug**
Empty lists throw an error

**To Reproduce**
Generate the i18n file using this json:
```json
{
  "title": "hi",
  "features": []
}
```

And add an interface:
```yaml
targets:
  $default:
    builders:
      fast_i18n:
        options:
          interfaces:
            Test: test
```

**Expected behavior**
Should render a getter returning an empty list. E.g. `List<String> features => [];`
